// src/modules/route-engine/constants/route-engine.constants.ts
import { AnalysisRoute } from '../enums/analysis-route.enum';

export const ROUTE_KEYWORDS: Record<AnalysisRoute, string[]> = {
  [AnalysisRoute.IDEA_NEGOCIO]: [
    'idea',
    'validar',
    'validacion',
    'validación',
    'emprender',
    'emprendimiento',
    'crear negocio',
    'nuevo negocio',
    'startup',
    'propuesta de valor',
    'problema',
    'cliente ideal',
  ],
  [AnalysisRoute.NEGOCIO_EXISTENTE]: [
    'empresa',
    'negocio',
    'operando',
    'operativo',
    'ventas',
    'caja',
    'costos',
    'clientes',
    'deuda',
    'rentabilidad',
    'flujo de caja',
  ],
  [AnalysisRoute.INVERSION]: [
    'invertir',
    'inversion',
    'inversión',
    'retorno',
    'rentabilidad',
    'liquidez',
    'volatilidad',
    'portafolio',
    'capital',
    'riesgo',
    'activo financiero',
    'cripto',
    'acciones',
    'bono',
    'fondo',
  ],
  [AnalysisRoute.ACTIVO_DIGITAL]: [
    'activo digital',
    'saas',
    'software',
    'app',
    'aplicacion',
    'aplicación',
    'usuarios',
    'tráfico',
    'trafico',
    'retencion',
    'retención',
    'monetizacion',
    'monetización',
    'mrr',
  ],
  [AnalysisRoute.FRANQUICIA]: [
    'franquicia',
    'canon',
    'royalty',
    'royalties',
    'marca',
    'sistema de franquicia',
    'licencia',
  ],
  [AnalysisRoute.EXPANSION]: [
    'expansion',
    'expansión',
    'abrir',
    'nueva sede',
    'nueva sucursal',
    'crecer',
    'escalar',
    'nuevo mercado',
    'expandir',
  ],
  [AnalysisRoute.COMPRA_EMPRESA]: [
    'comprar empresa',
    'compra de empresa',
    'adquirir',
    'adquisicion',
    'adquisición',
    'due diligence',
    'pasivos',
    'integracion',
    'integración',
    'm&a',
  ],
  [AnalysisRoute.COMPARACION]: [
    'comparar',
    'comparacion',
    'comparación',
    'opciones',
    'alternativas',
    'evaluar dos',
    'evaluar varias',
    'comparativa',
  ],
};

export const ROUTE_CONFIDENCE_MIN = 0.55;
export const ROUTE_CONFIDENCE_MAX = 0.98;